## Numpy

In [1]:
import numpy as np

In [2]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [3]:
two_d = np.array([range(i,i+3) for i in [2,4,6]])

In [4]:
two_d[1:,1:]

array([[5, 6],
       [7, 8]])

In [5]:
two_d[1:,0:2]

array([[4, 5],
       [6, 7]])

In [6]:
two_d[0:2,1:]

array([[3, 4],
       [5, 6]])

In [7]:
two_dx2 = two_d * 2
two_dx2

array([[ 4,  6,  8],
       [ 8, 10, 12],
       [12, 14, 16]])

In [8]:
np.concatenate((two_d, two_dx2))

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 4,  6,  8],
       [ 8, 10, 12],
       [12, 14, 16]])

In [9]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
my_ndarray = np.array([[2,3,4],[5,7,12],[10,1,3],[7,2,5]])

In [11]:
my_ndarray

array([[ 2,  3,  4],
       [ 5,  7, 12],
       [10,  1,  3],
       [ 7,  2,  5]])

In [12]:
my_ndarray.T

array([[ 2,  5, 10,  7],
       [ 3,  7,  1,  2],
       [ 4, 12,  3,  5]])

In [13]:
x = np.arange(1,6)
print(x)
np.add.reduce(x)


[1 2 3 4 5]


np.int64(15)

In [14]:
np.min(my_ndarray)
np.max(my_ndarray)
np.sum(my_ndarray)
np.multiply.reduce(x)
my_ndarray.sum()
np.multiply.reduce(my_ndarray)

array([700,  42, 720])

## Computation on arrays

In [15]:
my_ndarray_t = my_ndarray.T
my_ndarray_t

array([[ 2,  5, 10,  7],
       [ 3,  7,  1,  2],
       [ 4, 12,  3,  5]])

In [16]:
my_ndarray * my_ndarray

array([[  4,   9,  16],
       [ 25,  49, 144],
       [100,   1,   9],
       [ 49,   4,  25]])

## Dog Product

In [17]:
new_ar = np.random.random((3,3))
new_ar.dot(my_ndarray.T)
new_ar.shape
my_ndarray.shape

(4, 3)

In [18]:
import numpy as nu
nu.array([range(i,i+3) for i in [0,3,6]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
matrix = np.arange(9).reshape(3,3)

In [20]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
# replace all odd numbers with -1
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])
arr[0:11:2]=-1
#arr[arr % 2 != 0]
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1])

In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])
arr[arr > 7]
# or arr[7:11:1]

array([ 8,  9, 10, 11])

## PANDAS

In [23]:
import pandas as pd

In [24]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])

In [25]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [26]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [27]:
data[:2]

0    0.25
1    0.50
dtype: float64

In [28]:
data = pd.Series({2: 'a', 3: 'b', 4: 'c'})

In [29]:
data

2    a
3    b
4    c
dtype: object

## Creating a pandas dataframe

In [30]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Kenneth', 'Sandra'],
    'Age': [24, 28, 22, 35, np.nan],
    'City': ['Edo', 'Ibadan', 'Warri', 'Edo', np.nan]
}
data = pd.DataFrame(data)
data

,Name,Age,City
0,Alice,24.0,Edo
1,Bob,28.0,Ibadan
2,Charlie,22.0,Warri
3,Kenneth,35.0,Edo
4,Sandra,NaN,NaN


In [31]:
data[(data['Age'] > 22) & (data['City'] == 'Edo')]

,Name,Age,City
0,Alice,24.0,Edo
3,Kenneth,35.0,Edo


In [32]:
data['Age'].sum()

np.float64(109.0)

In [33]:
data['Age'].mean()

np.float64(27.25)

In [34]:
data['Math Score'] = [70,32,58,81,60]

data

,Name,Age,City,Math Score
0,Alice,24.0,Edo,70
1,Bob,28.0,Ibadan,32
2,Charlie,22.0,Warri,58
3,Kenneth,35.0,Edo,81
4,Sandra,NaN,NaN,60


In [35]:
data['English Score'] = [85, 81, 73, 92, 70]
data['score'] = (data['Math Score'] + data['English Score']) / 2
data

,Name,Age,City,Math Score,English Score,score
0,Alice,24.0,Edo,70,85,77.5
1,Bob,28.0,Ibadan,32,81,56.5
2,Charlie,22.0,Warri,58,73,65.5
3,Kenneth,35.0,Edo,81,92,86.5
4,Sandra,NaN,NaN,60,70,65.0


In [36]:
len(data['City'])

5

### Data Cleaning

In [37]:
mean_age = data['Age'].mean()
data['Age'] = data['Age'].fillna(mean_age)
data

,Name,Age,City,Math Score,English Score,score
0,Alice,24.00,Edo,70,85,77.5
1,Bob,28.00,Ibadan,32,81,56.5
2,Charlie,22.00,Warri,58,73,65.5
3,Kenneth,35.00,Edo,81,92,86.5
4,Sandra,27.25,NaN,60,70,65.0


In [38]:
new_city = 'Lagos'
data['City'] = data['City'].fillna(new_city)
data

,Name,Age,City,Math Score,English Score,score
0,Alice,24.00,Edo,70,85,77.5
1,Bob,28.00,Ibadan,32,81,56.5
2,Charlie,22.00,Warri,58,73,65.5
3,Kenneth,35.00,Edo,81,92,86.5
4,Sandra,27.25,Lagos,60,70,65.0


In [39]:
data.iloc[0,5] = 67
data.iloc[0:5, 3:5] + 10

,Math Score,English Score
0,80,95
1,42,91
2,68,83
3,91,102
4,70,80


In [40]:
data

,Name,Age,City,Math Score,English Score,score
0,Alice,24.00,Edo,70,85,67.0
1,Bob,28.00,Ibadan,32,81,56.5
2,Charlie,22.00,Warri,58,73,65.5
3,Kenneth,35.00,Edo,81,92,86.5
4,Sandra,27.25,Lagos,60,70,65.0


In [41]:
data = pd.Series([1, np.nan, 'hello', None])

In [42]:
data.isnull

<bound method Series.isnull of 0        1
1      NaN
2    hello
3     None
dtype: object>

In [43]:
data.dropna()

0        1
2    hello
dtype: object

In [44]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [45]:
df = pd.DataFrame([[1, np.nan, 2], [2,3,5], [np.nan, 4, 6]])
df

,0,1,2
0,1.0,NaN,2
1,2.0,3.0,5
2,NaN,4.0,6


In [46]:
df[3]=9
df[4]= [5, np.nan, 6]
df

,0,1,2,3,4
0,1.0,NaN,2,9,5.0
1,2.0,3.0,5,9,NaN
2,NaN,4.0,6,9,6.0


In [47]:
df.dropna(axis=1)

,2,3
0,2,9
1,5,9
2,6,9


In [41]:
#df.dropna(inplace=True)

In [48]:
df.fillna(0)

,0,1,2,3,4
0,1.0,0.0,2,9,5.0
1,2.0,3.0,5,9,0.0
2,0.0,4.0,6,9,6.0


In [49]:
df

,0,1,2,3,4
0,1.0,NaN,2,9,5.0
1,2.0,3.0,5,9,NaN
2,NaN,4.0,6,9,6.0


In [50]:
df.ffill()

,0,1,2,3,4
0,1.0,NaN,2,9,5.0
1,2.0,3.0,5,9,5.0
2,2.0,4.0,6,9,6.0


In [6]:
!pip install torchvision

   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.1 MB ? eta -:--:--
   ---------- ----------------------------- 1.0/4.1 MB 3.3 MB/s eta 0:00:01
   -------------------- ------------------- 2.1/4.1 MB 3.8 MB/s eta 0:00:01
   ---------------------------- ----------- 2.9/4.1 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 3.9/4.1 MB 4.1 MB/s eta 0:00:01
   -------------------------------------- - 3.9/4.1 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 4.1/4.1 MB 3.3 MB/s  0:00:01
   ---------------------------------------- 0.0/123.0 MB ? eta -:--:--
   ---------------------------------------- 0.8/123.0 MB 5.2 MB/s eta 0:00:24
   ---------------------------------------- 1.3/123.0 MB 4.2 MB/s eta 0:00:29
    --------------------------------------- 2.4/123.0 MB 3.7 MB/s eta 0:00:33
    -------------------------------

In [7]:
from torchvision import models

In [4]:
def factorial(n):
    if n == 1:
        return 1
    return factorial(n-1)*n

factorial(5)

120

### Write a recursive function to find the nth fibonnacci number.

### Fibonnacci number: 0 1 1 2 3 5 8 13 21 34

### Input: 9
### Output: 21

In [24]:
#Fibonnacci_number= 0, 1, 1, 2, 3, 5, 8, 13, 21, 34
#Fibonnacci_number[0+4+1]

5

In [41]:
#Fibonnacci number: 0 1 1 2 3 5 8 13 21 34
def fibonacci_recursive(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci_recursive(n-1) + fibonacci_recursive(n-2)

print(fibonacci_recursive(3))

2
